
#define STEERING_SOURCE 22
#define THROTTLE_SOURCE 23
#define BRAKE_SOURCE 24
#define BUTTON_SOURCE 25
#define THROTTLE_OUTPUT_PIN 26
#define STEERING_OUTPUT_PIN 28
#define STEERING_LEFT_LIMITER 29
#define STEERING_RIGHT_LIMITER 30
#define SPEED_SENSOR_INPUT_PIN A0
#define STEERING_ANGLE_SENSOR A1
#define SPI_CS_PIN 9
#define CAN_INT_PIN 2