
#define STEERING_SOURCE 2
#define THROTTLE_SOURCE 3
#define BRAKE_SOURCE 4
#define BUTTON_SOURCE 5
#define STEERING_OUTPUT_PIN 6
#define BRAKE_OUTPUT_PIN 7
#define THROTTLE_OUTPUT_PIN 8
#define SPEED_SENSOR_INPUT_PIN A0
